//! Emit — IR → on-disk Rust crate.
//!
//! Three outputs, one per file the generated crate needs:
//!
//!   - `Cargo.toml` (package manifest)
//!   - `src/lib.rs` (the typed structs + register fn)
//!   - `README.md` (one-paragraph what-it-is)
//!
//! Hermetic: the emitter takes IR + options and returns strings.
//! No I/O. The CLI binary is what writes them to disk. Keeps the
//! library testable and lets downstream pipelines (e.g. embedding
//! the forge in another Rust binary) compose freely.

use crate::ir::{Domain, DomainKind, Field, FieldType, Resource};
use std::fmt::Write;

/// Knobs that don't fit naturally on the `Domain` IR — author /
/// version metadata, dependency override, workspace integration.
#[derive(Debug, Clone)]
pub struct EmitOptions {
    pub author: String,
    pub version: String,
    /// Path to the `tatara-lisp-derive` dependency. Defaults to a
    /// crates.io version pin; embedders building inside the
    /// `tatara-lisp` workspace should override to a path-dep.
    pub tatara_lisp_derive_dep: String,
    /// Path to the `tatara-lisp` dependency (provides the
    /// `TataraDomain` trait + helpers).
    pub tatara_lisp_dep: String,
    /// When `true`, emit a Cargo.toml that inherits `version` /
    /// `edition` / `authors` / `license` / `repository` /
    /// `homepage` from the parent workspace, sets
    /// `[lints] workspace = true`, and assumes path-deps for
    /// `tatara-lisp{,-derive}`. Use when generating a crate as a
    /// new member of an existing workspace (vs a standalone
    /// repo) — the generated crate just slots in.
    pub workspace_member: bool,
}

impl Default for EmitOptions {
    fn default() -> Self {
        Self {
            author: "Pleme.io <engineering@pleme.io>".into(),
            version: "0.1.0".into(),
            tatara_lisp_derive_dep: "{ version = \"0.2\" }".into(),
            tatara_lisp_dep: "{ version = \"0.2\" }".into(),
            workspace_member: false,
        }
    }
}

impl EmitOptions {
    /// Preset for "this crate joins the tatara-lisp workspace as a
    /// member". Switches to path-deps and workspace-inheritance.
    #[must_use]
    pub fn workspace_member() -> Self {
        Self {
            workspace_member: true,
            tatara_lisp_derive_dep: "{ path = \"../tatara-lisp-derive\" }".into(),
            tatara_lisp_dep: "{ path = \"../tatara-lisp\" }".into(),
            ..Default::default()
        }
    }
}

/// Render a Cargo.toml for the generated crate.
#[must_use]
pub fn emit_cargo_toml(domain: &Domain, opts: &EmitOptions) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "[package]");
    let _ = writeln!(out, "name = \"{}\"", domain.name);
    let _ = writeln!(out, "description = \"{}\"", escape_toml(&domain.description));
    if opts.workspace_member {
        let _ = writeln!(out, "version.workspace = true");
        let _ = writeln!(out, "edition.workspace = true");
        let _ = writeln!(out, "authors.workspace = true");
        let _ = writeln!(out, "license.workspace = true");
        let _ = writeln!(out, "repository.workspace = true");
        let _ = writeln!(out, "homepage.workspace = true");
        let _ = writeln!(out);
        let _ = writeln!(out, "[lints]");
        let _ = writeln!(out, "workspace = true");
    } else {
        let _ = writeln!(out, "version = \"{}\"", opts.version);
        let _ = writeln!(out, "edition = \"2021\"");
        let _ = writeln!(out, "authors = [\"{}\"]", opts.author);
        let _ = writeln!(out, "license = \"MIT\"");
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "[dependencies]");
    let _ = writeln!(
        out,
        "tatara-lisp-derive = {}",
        opts.tatara_lisp_derive_dep
    );
    let _ = writeln!(out, "tatara-lisp = {}", opts.tatara_lisp_dep);
    let _ = writeln!(out, "serde = {{ version = \"1\", features = [\"derive\"] }}");
    let _ = writeln!(out, "serde_json = \"1\"");
    out
}

/// Render `src/lib.rs` — structs, enums, register fn, doc.
///
/// Two-pass: walk the IR collecting every type definition into a
/// `Pending` queue keyed by Rust name. Resolve types-by-name in the
/// queue, then emit them in collected order. Avoids the trap where
/// a child struct's body gets written mid-emission of its parent.
#[must_use]
pub fn emit_lib_rs(domain: &Domain) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "//! {} — auto-generated tatara domain.", domain.name);
    let _ = writeln!(out, "//!");
    let _ = writeln!(out, "//! {}", domain.description);
    let _ = writeln!(out, "//!");
    let _ = writeln!(
        out,
        "//! Generated by `tatara-domain-forge`. Do not hand-edit."
    );
    let _ = writeln!(out, "//! Re-run the generator to refresh.");
    let _ = writeln!(out);
    let _ = writeln!(out, "#![allow(clippy::module_name_repetitions)]");
    let _ = writeln!(out);
    let _ = writeln!(out, "use serde::{{Deserialize, Serialize}};");
    let _ = writeln!(out, "use tatara_lisp_derive::TataraDomain;");
    let _ = writeln!(out);

    // Pass 1: collect every nested type definition into `pending`.
    // Emit each top-level Resource struct directly into `out` —
    // type references in those struct bodies just name the nested
    // types, which we'll define after.
    let mut pending: Vec<(String, String)> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    for r in &domain.resources {
        emit_resource_struct(r, &mut out, &mut pending, &mut seen);
    }

    // Pass 2: emit collected nested types in deterministic order.
    if !pending.is_empty() {
        let _ = writeln!(out, "// ── Nested types ──────────────────────────────────────");
    }
    for (_name, body) in pending {
        out.push_str(&body);
    }

    // Emit `impl RenderableDomain` for every resource that has
    // K8s metadata available — drives the auto-render path in
    // `tatara-render::KubernetesYaml::render_via_registry`.
    let any_renderable = domain
        .resources
        .iter()
        .any(|r| r.api_version.is_some() && r.kind.is_some());
    if any_renderable {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "// ── Render metadata (consumed by tatara-render) ──────────"
        );
        for r in &domain.resources {
            if let (Some(api), Some(kind)) = (&r.api_version, &r.kind) {
                let name_field = r.name_field.as_deref().unwrap_or("name");
                let _ = writeln!(out);
                let _ = writeln!(out, "impl tatara_lisp::RenderableDomain for {} {{", r.struct_name);
                let _ = writeln!(out, "    const API_VERSION: &'static str = {api:?};");
                let _ = writeln!(out, "    const KIND: &'static str = {kind:?};");
                let _ = writeln!(out, "    const NAME_FIELD: &'static str = {name_field:?};");
                let _ = writeln!(out, "}}");
            }
        }
    }

    // Emit `impl DocumentedDomain` — third capability layer.
    // Carries the type's CRD description + per-field descriptions
    // for catalog browsers + the `tatara doc` CLI.
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "// ── Documentation metadata (consumed by tatara-doc / IDE) ──"
    );
    for r in &domain.resources {
        let docstring = r
            .doc
            .as_deref()
            .map(|s| escape_rust_str(&one_line(s)))
            .unwrap_or_default();
        let _ = writeln!(out);
        let _ = writeln!(out, "impl tatara_lisp::DocumentedDomain for {} {{", r.struct_name);
        let _ = writeln!(out, "    const DOCSTRING: &'static str = \"{docstring}\";");
        let _ = writeln!(
            out,
            "    const FIELD_DOCS: &'static [(&'static str, &'static str)] = &["
        );
        for (rust_name, field) in &r.fields {
            if let Some(d) = &field.doc {
                let escaped = escape_rust_str(&one_line(d));
                let _ = writeln!(out, "        ({rust_name:?}, \"{escaped}\"),");
            }
        }
        let _ = writeln!(out, "    ];");
        let _ = writeln!(out, "}}");
    }

    // Emit register fn — wires every Resource's keyword form into
    // an `Interpreter<H>`'s domain registry. When render metadata
    // is available, also wires the render handler.
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "/// Register every keyword form this domain exposes onto the host"
    );
    let _ = writeln!(
        out,
        "/// interpreter. Embedders call this once during boot."
    );
    let _ = writeln!(out, "pub fn register() {{");
    for r in &domain.resources {
        let _ = writeln!(
            out,
            "    tatara_lisp::domain::register::<{}>();",
            r.struct_name
        );
        if r.api_version.is_some() && r.kind.is_some() {
            let _ = writeln!(
                out,
                "    tatara_lisp::domain::register_render::<{}>();",
                r.struct_name
            );
        }
        let _ = writeln!(
            out,
            "    tatara_lisp::domain::register_doc::<{}>();",
            r.struct_name
        );
    }
    let _ = writeln!(out, "}}");
    out
}

/// Collapse a multi-line CRD description to a single line so it
/// fits in a Rust string literal cleanly. Newlines become spaces;
/// runs of whitespace collapse.
fn one_line(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Escape a string for inclusion in `"…"` Rust source — escape
/// backslash + quote. Newlines already gone via `one_line`.
fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn emit_resource_struct(
    r: &Resource,
    out: &mut String,
    pending: &mut Vec<(String, String)>,
    seen: &mut std::collections::HashSet<String>,
) {
    if let Some(d) = &r.doc {
        for line in d.lines() {
            let _ = writeln!(out, "/// {}", line.trim());
        }
    }
    let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize, TataraDomain)]");
    let _ = writeln!(out, "#[tatara(keyword = \"{}\")]", r.keyword);
    let _ = writeln!(out, "pub struct {} {{", r.struct_name);
    for (rust_name, field) in &r.fields {
        emit_field_into(rust_name, field, out, pending, seen);
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

/// Emit a field declaration into `target`. Side effect: any nested
/// types (struct or enum) that the field's type references are
/// queued in `pending` for later emission. `seen` dedupes by name
/// so the same nested type isn't emitted twice if it's referenced
/// from multiple parents.
fn emit_field_into(
    rust_name: &str,
    field: &Field,
    target: &mut String,
    pending: &mut Vec<(String, String)>,
    seen: &mut std::collections::HashSet<String>,
) {
    if let Some(d) = &field.doc {
        for line in d.lines() {
            let _ = writeln!(target, "    /// {}", line.trim());
        }
    }
    let serde_attr = if field.required {
        String::new()
    } else {
        "    #[serde(default)]\n".to_string()
    };
    let ty_str = render_type(&field.ty, pending, seen);
    let final_ty = if field.required {
        ty_str
    } else {
        format!("Option<{ty_str}>")
    };
    target.push_str(&serde_attr);
    let _ = writeln!(target, "    pub {rust_name}: {final_ty},");
}

/// Render a `FieldType` as a Rust type expression. Side effect:
/// `Nested` and `Enum` types' definitions are queued in `pending`,
/// keyed by name (dedupe via `seen`). Recursive: a Nested whose
/// fields reference further nested types queues those too.
fn render_type(
    ty: &FieldType,
    pending: &mut Vec<(String, String)>,
    seen: &mut std::collections::HashSet<String>,
) -> String {
    match ty {
        FieldType::Scalar(s) => s.rust_str().to_string(),
        FieldType::List(inner) => format!("Vec<{}>", render_type(inner, pending, seen)),
        FieldType::Map(inner) => {
            format!(
                "std::collections::HashMap<String, {}>",
                render_type(inner, pending, seen)
            )
        }
        FieldType::Nested {
            struct_name,
            fields,
        } => {
            if seen.insert(struct_name.clone()) {
                // Emit child's body into a fresh buffer so its
                // contents are contiguous regardless of recursive
                // emit ordering.
                let mut body = String::new();
                let _ = writeln!(body, "#[derive(Debug, Clone, Serialize, Deserialize)]");
                let _ = writeln!(body, "pub struct {struct_name} {{");
                for (n, f) in fields {
                    emit_field_into(n, f, &mut body, pending, seen);
                }
                let _ = writeln!(body, "}}");
                let _ = writeln!(body);
                pending.push((struct_name.clone(), body));
            }
            struct_name.clone()
        }
        FieldType::Enum {
            type_name,
            variants,
        } => {
            if seen.insert(type_name.clone()) {
                let mut body = String::new();
                let _ = writeln!(body, "#[derive(Debug, Clone, Serialize, Deserialize)]");
                let _ = writeln!(body, "pub enum {type_name} {{");
                // Some upstream CRDs accept multiple casings for the
                // same logical value (e.g. prometheus-operator's
                // `RelabelAction` allows both `replace` and `Replace`).
                // Both pascal-case to `Replace`, which is a Rust
                // duplicate-variant error. Track emitted idents and
                // suffix collisions with `_N` so each variant lands a
                // unique name; serde's #[serde(rename = "<source>")]
                // preserves the wire form correctly either way.
                let mut local_seen: std::collections::HashMap<String, usize> =
                    std::collections::HashMap::new();
                for v in variants {
                    let base = variant_pascal(v);
                    let n = local_seen.entry(base.clone()).or_insert(0);
                    // Suffix without underscore — keeps idents in
                    // valid UpperCamelCase per Rust naming lints.
                    let ident = if *n == 0 {
                        base.clone()
                    } else {
                        format!("{base}V{n}")
                    };
                    *n += 1;
                    let _ = writeln!(body, "    #[serde(rename = \"{v}\")]");
                    let _ = writeln!(body, "    {ident},");
                }
                let _ = writeln!(body, "}}");
                let _ = writeln!(body);
                pending.push((type_name.clone(), body));
            }
            type_name.clone()
        }
        FieldType::Untyped => "serde_json::Value".to_string(),
    }
}

fn variant_pascal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut up = true;
    for c in s.chars() {
        if c.is_alphanumeric() {
            if up {
                out.extend(c.to_uppercase());
                up = false;
            } else {
                out.push(c);
            }
        } else {
            up = true;
        }
    }
    if out.is_empty() {
        out.push('X');
    }
    if out.chars().next().map_or(true, |c| c.is_ascii_digit()) {
        out.insert(0, 'V');
    }
    out
}

/// Convenience: emit just the register fn body (caller embeds in
/// their own lib.rs). Currently unused externally — exposed for
/// downstream pipelines that want finer control.
#[must_use]
pub fn emit_register_fn(domain: &Domain) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "pub fn register() {{");
    for r in &domain.resources {
        let _ = writeln!(
            out,
            "    tatara_lisp::domain::register::<{}>();",
            r.struct_name
        );
    }
    let _ = writeln!(out, "}}");
    out
}

/// Render a one-page README explaining the crate's surface.
#[must_use]
pub fn emit_readme(domain: &Domain) -> String {
    let kind = match domain.kind {
        DomainKind::Kubernetes => "Kubernetes CRDs",
        DomainKind::OpenApi => "an OpenAPI 3.0 schema",
        DomainKind::Hand => "a hand-authored TOML spec",
    };
    let mut out = String::new();
    let _ = writeln!(out, "# {}", domain.name);
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", domain.description);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Auto-generated by `tatara-domain-forge` from {kind}."
    );
    let _ = writeln!(out, "Re-run the generator to refresh — hand edits will be overwritten.");
    let _ = writeln!(out);
    let _ = writeln!(out, "## Resources");
    let _ = writeln!(out);
    for r in &domain.resources {
        let _ = writeln!(out, "- `{}` — `{}`", r.keyword, r.struct_name);
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "## Usage");
    let _ = writeln!(out);
    let _ = writeln!(out, "```rust,no_run");
    let _ = writeln!(out, "fn main() {{");
    let _ = writeln!(out, "    {}::register();", domain.name.replace('-', "_"));
    let _ = writeln!(out, "    // …drive an Interpreter as usual");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "```");
    out
}

fn escape_toml(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::from_crd_str;

    const TINY_CRD: &str = r#"
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: monitors.test.io
spec:
  group: test.io
  names: {kind: Monitor, plural: monitors}
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: [name, query]
            properties:
              name: {type: string}
              query: {type: string}
              threshold: {type: number}
              labels:
                type: object
                additionalProperties: {type: string}
              severity:
                type: string
                enum: [info, warn, critical]
"#;

    #[test]
    fn emit_lib_rs_for_simple_crd_compiles_smoke_test() {
        let d = from_crd_str(TINY_CRD, "tatara-test").unwrap();
        let lib = emit_lib_rs(&d);
        // Sanity: the structs + keyword + register fn all appear.
        assert!(lib.contains("pub struct MonitorSpec"));
        assert!(lib.contains("#[tatara(keyword = \"defmonitor\")]"));
        assert!(lib.contains("pub fn register()"));
        assert!(lib.contains("tatara_lisp::domain::register::<MonitorSpec>()"));
        // Required fields are bare; optional fields wrap in Option<…>.
        assert!(lib.contains("pub name: String,"));
        assert!(lib.contains("pub query: String,"));
        assert!(lib.contains("pub threshold: Option<f64>,"));
        // labels lowered to HashMap<String, String>.
        assert!(lib.contains("pub labels: Option<std::collections::HashMap<String, String>>"));
        // severity emitted as a separate enum.
        assert!(lib.contains("pub enum"));
        assert!(lib.contains("#[serde(rename = \"info\")]"));
        assert!(lib.contains("Critical,"));
    }

    #[test]
    fn emit_cargo_toml_pulls_required_deps() {
        let d = from_crd_str(TINY_CRD, "tatara-test").unwrap();
        let cargo = emit_cargo_toml(&d, &EmitOptions::default());
        assert!(cargo.contains("name = \"tatara-test\""));
        assert!(cargo.contains("tatara-lisp-derive"));
        assert!(cargo.contains("tatara-lisp"));
        assert!(cargo.contains("serde = "));
    }

    #[test]
    fn emit_readme_lists_every_resource() {
        let d = from_crd_str(TINY_CRD, "tatara-test").unwrap();
        let r = emit_readme(&d);
        assert!(r.contains("# tatara-test"));
        assert!(r.contains("`defmonitor`"));
        assert!(r.contains("`MonitorSpec`"));
    }

    #[test]
    fn variant_pascal_handles_ugly_inputs() {
        assert_eq!(variant_pascal("info"), "Info");
        assert_eq!(variant_pascal("warn-level"), "WarnLevel");
        assert_eq!(variant_pascal("LoadBalancer"), "LoadBalancer");
        // Numeric leading char prefixed with V.
        assert_eq!(variant_pascal("3xx"), "V3xx");
    }
}
