//! tatara-prometheus-operator — auto-generated tatara domain.
//!
//! Tatara domain wrapping 1 CRD(s).
//!
//! Generated by `tatara-domain-forge`. Do not hand-edit.
//! Re-run the generator to refresh.

#![allow(clippy::module_name_repetitions)]

use serde::{Deserialize, Serialize};
use tatara_lisp_derive::TataraDomain;

/// The `PodMonitor` custom resource definition (CRD) defines how `Prometheus` and `PrometheusAgent` can scrape metrics from a group of pods.
/// Among other things, it allows to specify:
/// * The pods to scrape via label selectors.
/// * The container ports to scrape.
/// * Authentication credentials to use.
/// * Target and metric relabeling.
/// 
/// `Prometheus` and `PrometheusAgent` objects select `PodMonitor` objects using label and namespace selectors.
#[derive(Debug, Clone, Serialize, Deserialize, TataraDomain)]
#[tatara(keyword = "defpodmonitor")]
pub struct PodMonitorSpec {
    /// `attachMetadata` defines additional metadata which is added to the
    /// discovered targets.
    /// 
    /// It requires Prometheus >= v2.35.0.
    #[serde(default)]
    pub attach_metadata: Option<PodMonitorAttachMetadata>,
    /// When defined, bodySizeLimit specifies a job level limit on the size
    /// of uncompressed response body that will be accepted by Prometheus.
    /// 
    /// It requires Prometheus >= v2.28.0.
    #[serde(default)]
    pub body_size_limit: Option<String>,
    /// The protocol to use if a scrape returns blank, unparseable, or otherwise invalid Content-Type.
    /// 
    /// It requires Prometheus >= v3.0.0.
    #[serde(default)]
    pub fallback_scrape_protocol: Option<PodMonitorFallbackScrapeProtocolKind>,
    /// The label to use to retrieve the job name from.
    /// `jobLabel` selects the label from the associated Kubernetes `Pod`
    /// object which will be used as the `job` label for all metrics.
    /// 
    /// For example if `jobLabel` is set to `foo` and the Kubernetes `Pod`
    /// object is labeled with `foo: bar`, then Prometheus adds the `job="bar"`
    /// label to all ingested metrics.
    /// 
    /// If the value of this field is empty, the `job` label of the metrics
    /// defaults to the namespace and name of the PodMonitor object (e.g. `<namespace>/<name>`).
    #[serde(default)]
    pub job_label: Option<String>,
    /// Per-scrape limit on the number of targets dropped by relabeling
    /// that will be kept in memory. 0 means no limit.
    /// 
    /// It requires Prometheus >= v2.47.0.
    #[serde(default)]
    pub keep_dropped_targets: Option<i64>,
    /// Per-scrape limit on number of labels that will be accepted for a sample.
    /// 
    /// It requires Prometheus >= v2.27.0.
    #[serde(default)]
    pub label_limit: Option<i64>,
    /// Per-scrape limit on length of labels name that will be accepted for a sample.
    /// 
    /// It requires Prometheus >= v2.27.0.
    #[serde(default)]
    pub label_name_length_limit: Option<i64>,
    /// Per-scrape limit on length of labels value that will be accepted for a sample.
    /// 
    /// It requires Prometheus >= v2.27.0.
    #[serde(default)]
    pub label_value_length_limit: Option<i64>,
    /// `namespaceSelector` defines in which namespace(s) Prometheus should discover the pods.
    /// By default, the pods are discovered in the same namespace as the `PodMonitor` object but it is possible to select pods across different/all namespaces.
    #[serde(default)]
    pub namespace_selector: Option<PodMonitorNamespaceSelector>,
    /// If there are more than this many buckets in a native histogram,
    /// buckets will be merged to stay within the limit.
    /// It requires Prometheus >= v2.45.0.
    #[serde(default)]
    pub native_histogram_bucket_limit: Option<i64>,
    /// If the growth factor of one bucket to the next is smaller than this,
    /// buckets will be merged to increase the factor sufficiently.
    /// It requires Prometheus >= v2.50.0.
    #[serde(default)]
    pub native_histogram_min_bucket_factor: Option<serde_json::Value>,
    /// Defines how to scrape metrics from the selected pods.
    #[serde(default)]
    pub pod_metrics_endpoints: Option<Vec<PodMonitorPodMetricsEndpointsItem>>,
    /// `podTargetLabels` defines the labels which are transferred from the
    /// associated Kubernetes `Pod` object onto the ingested metrics.
    #[serde(default)]
    pub pod_target_labels: Option<Vec<String>>,
    /// `sampleLimit` defines a per-scrape limit on the number of scraped samples
    /// that will be accepted.
    #[serde(default)]
    pub sample_limit: Option<i64>,
    /// The scrape class to apply.
    #[serde(default)]
    pub scrape_class: Option<String>,
    /// Whether to scrape a classic histogram that is also exposed as a native histogram.
    /// It requires Prometheus >= v2.45.0.
    #[serde(default)]
    pub scrape_classic_histograms: Option<bool>,
    /// `scrapeProtocols` defines the protocols to negotiate during a scrape. It tells clients the
    /// protocols supported by Prometheus in order of preference (from most to least preferred).
    /// 
    /// If unset, Prometheus uses its default value.
    /// 
    /// It requires Prometheus >= v2.49.0.
    #[serde(default)]
    pub scrape_protocols: Option<Vec<PodMonitorScrapeProtocolsItemKind>>,
    /// Label selector to select the Kubernetes `Pod` objects to scrape metrics from.
    pub selector: PodMonitorSelector,
    /// Mechanism used to select the endpoints to scrape.
    /// By default, the selection process relies on relabel configurations to filter the discovered targets.
    /// Alternatively, you can opt in for role selectors, which may offer better efficiency in large clusters.
    /// Which strategy is best for your use case needs to be carefully evaluated.
    /// 
    /// It requires Prometheus >= v2.17.0.
    #[serde(default)]
    pub selector_mechanism: Option<PodMonitorSelectorMechanismKind>,
    /// `targetLimit` defines a limit on the number of scraped targets that will
    /// be accepted.
    #[serde(default)]
    pub target_limit: Option<i64>,
}

// ── Nested types ──────────────────────────────────────
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorAttachMetadata {
    /// When set to true, Prometheus attaches node metadata to the discovered
    /// targets.
    /// 
    /// The Prometheus service account must have the `list` and `watch`
    /// permissions on the `Nodes` objects.
    #[serde(default)]
    pub node: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorFallbackScrapeProtocolKind {
    #[serde(rename = "PrometheusProto")]
    PrometheusProto,
    #[serde(rename = "OpenMetricsText0.0.1")]
    OpenMetricsText001,
    #[serde(rename = "OpenMetricsText1.0.0")]
    OpenMetricsText100,
    #[serde(rename = "PrometheusText0.0.4")]
    PrometheusText004,
    #[serde(rename = "PrometheusText1.0.0")]
    PrometheusText100,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorNamespaceSelector {
    /// Boolean describing whether all namespaces are selected in contrast to a
    /// list restricting them.
    #[serde(default)]
    pub any: Option<bool>,
    /// List of namespace names to select from.
    #[serde(default)]
    pub match_names: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemAuthorizationCredentials {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemAuthorization {
    /// Selects a key of a Secret in the namespace that contains the credentials for authentication.
    #[serde(default)]
    pub credentials: Option<PodMonitorPodMetricsEndpointsItemAuthorizationCredentials>,
    /// Defines the authentication type. The value is case-insensitive.
    /// 
    /// "Basic" is not a supported value.
    /// 
    /// Default: "Bearer"
    #[serde(default)]
    pub r#type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemBasicAuthPassword {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemBasicAuthUsername {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemBasicAuth {
    /// `password` specifies a key of a Secret containing the password for
    /// authentication.
    #[serde(default)]
    pub password: Option<PodMonitorPodMetricsEndpointsItemBasicAuthPassword>,
    /// `username` specifies a key of a Secret containing the username for
    /// authentication.
    #[serde(default)]
    pub username: Option<PodMonitorPodMetricsEndpointsItemBasicAuthUsername>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemBearerTokenSecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorPodMetricsEndpointsItemMetricRelabelingsItemActionKind {
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "Replace")]
    ReplaceV1,
    #[serde(rename = "keep")]
    Keep,
    #[serde(rename = "Keep")]
    KeepV1,
    #[serde(rename = "drop")]
    Drop,
    #[serde(rename = "Drop")]
    DropV1,
    #[serde(rename = "hashmod")]
    Hashmod,
    #[serde(rename = "HashMod")]
    HashMod,
    #[serde(rename = "labelmap")]
    Labelmap,
    #[serde(rename = "LabelMap")]
    LabelMap,
    #[serde(rename = "labeldrop")]
    Labeldrop,
    #[serde(rename = "LabelDrop")]
    LabelDrop,
    #[serde(rename = "labelkeep")]
    Labelkeep,
    #[serde(rename = "LabelKeep")]
    LabelKeep,
    #[serde(rename = "lowercase")]
    Lowercase,
    #[serde(rename = "Lowercase")]
    LowercaseV1,
    #[serde(rename = "uppercase")]
    Uppercase,
    #[serde(rename = "Uppercase")]
    UppercaseV1,
    #[serde(rename = "keepequal")]
    Keepequal,
    #[serde(rename = "KeepEqual")]
    KeepEqual,
    #[serde(rename = "dropequal")]
    Dropequal,
    #[serde(rename = "DropEqual")]
    DropEqual,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemMetricRelabelingsItem {
    /// Action to perform based on the regex matching.
    /// 
    /// `Uppercase` and `Lowercase` actions require Prometheus >= v2.36.0.
    /// `DropEqual` and `KeepEqual` actions require Prometheus >= v2.41.0.
    /// 
    /// Default: "Replace"
    #[serde(default)]
    pub action: Option<PodMonitorPodMetricsEndpointsItemMetricRelabelingsItemActionKind>,
    /// Modulus to take of the hash of the source label values.
    /// 
    /// Only applicable when the action is `HashMod`.
    #[serde(default)]
    pub modulus: Option<i64>,
    /// Regular expression against which the extracted value is matched.
    #[serde(default)]
    pub regex: Option<String>,
    /// Replacement value against which a Replace action is performed if the
    /// regular expression matches.
    /// 
    /// Regex capture groups are available.
    #[serde(default)]
    pub replacement: Option<String>,
    /// Separator is the string between concatenated SourceLabels.
    #[serde(default)]
    pub separator: Option<String>,
    /// The source labels select values from existing labels. Their content is
    /// concatenated using the configured Separator and matched against the
    /// configured regular expression.
    #[serde(default)]
    pub source_labels: Option<Vec<String>>,
    /// Label to which the resulting string is written in a replacement.
    /// 
    /// It is mandatory for `Replace`, `HashMod`, `Lowercase`, `Uppercase`,
    /// `KeepEqual` and `DropEqual` actions.
    /// 
    /// Regex capture groups are available.
    #[serde(default)]
    pub target_label: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2ClientIdConfigMap {
    /// The key to select.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the ConfigMap or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2ClientIdSecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2ClientId {
    /// ConfigMap containing data to use for the targets.
    #[serde(default)]
    pub config_map: Option<PodMonitorPodMetricsEndpointsItemOauth2ClientIdConfigMap>,
    /// Secret containing data to use for the targets.
    #[serde(default)]
    pub secret: Option<PodMonitorPodMetricsEndpointsItemOauth2ClientIdSecret>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2ClientSecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2ProxyConnectHeaderValueItem {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCaConfigMap {
    /// The key to select.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the ConfigMap or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCaSecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCa {
    /// ConfigMap containing data to use for the targets.
    #[serde(default)]
    pub config_map: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCaConfigMap>,
    /// Secret containing data to use for the targets.
    #[serde(default)]
    pub secret: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCaSecret>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCertConfigMap {
    /// The key to select.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the ConfigMap or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCertSecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCert {
    /// ConfigMap containing data to use for the targets.
    #[serde(default)]
    pub config_map: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCertConfigMap>,
    /// Secret containing data to use for the targets.
    #[serde(default)]
    pub secret: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCertSecret>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfigKeySecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorPodMetricsEndpointsItemOauth2TlsConfigMaxVersionKind {
    #[serde(rename = "TLS10")]
    TLS10,
    #[serde(rename = "TLS11")]
    TLS11,
    #[serde(rename = "TLS12")]
    TLS12,
    #[serde(rename = "TLS13")]
    TLS13,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorPodMetricsEndpointsItemOauth2TlsConfigMinVersionKind {
    #[serde(rename = "TLS10")]
    TLS10,
    #[serde(rename = "TLS11")]
    TLS11,
    #[serde(rename = "TLS12")]
    TLS12,
    #[serde(rename = "TLS13")]
    TLS13,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2TlsConfig {
    /// Certificate authority used when verifying server certificates.
    #[serde(default)]
    pub ca: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCa>,
    /// Client certificate to present when doing client-authentication.
    #[serde(default)]
    pub cert: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigCert>,
    /// Disable target certificate validation.
    #[serde(default)]
    pub insecure_skip_verify: Option<bool>,
    /// Secret containing the client key file for the targets.
    #[serde(default)]
    pub key_secret: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigKeySecret>,
    /// Maximum acceptable TLS version.
    /// 
    /// It requires Prometheus >= v2.41.0.
    #[serde(default)]
    pub max_version: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigMaxVersionKind>,
    /// Minimum acceptable TLS version.
    /// 
    /// It requires Prometheus >= v2.35.0.
    #[serde(default)]
    pub min_version: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfigMinVersionKind>,
    /// Used to verify the hostname for the targets.
    #[serde(default)]
    pub server_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemOauth2 {
    /// `clientId` specifies a key of a Secret or ConfigMap containing the
    /// OAuth2 client's ID.
    pub client_id: PodMonitorPodMetricsEndpointsItemOauth2ClientId,
    /// `clientSecret` specifies a key of a Secret containing the OAuth2
    /// client's secret.
    pub client_secret: PodMonitorPodMetricsEndpointsItemOauth2ClientSecret,
    /// `endpointParams` configures the HTTP parameters to append to the token
    /// URL.
    #[serde(default)]
    pub endpoint_params: Option<std::collections::HashMap<String, String>>,
    /// `noProxy` is a comma-separated string that can contain IPs, CIDR notation, domain names
    /// that should be excluded from proxying. IP and domain names can
    /// contain port numbers.
    /// 
    /// It requires Prometheus >= v2.43.0 or Alertmanager >= 0.25.0.
    #[serde(default)]
    pub no_proxy: Option<String>,
    /// ProxyConnectHeader optionally specifies headers to send to
    /// proxies during CONNECT requests.
    /// 
    /// It requires Prometheus >= v2.43.0 or Alertmanager >= 0.25.0.
    #[serde(default)]
    pub proxy_connect_header: Option<std::collections::HashMap<String, Vec<PodMonitorPodMetricsEndpointsItemOauth2ProxyConnectHeaderValueItem>>>,
    /// Whether to use the proxy configuration defined by environment variables (HTTP_PROXY, HTTPS_PROXY, and NO_PROXY).
    /// 
    /// It requires Prometheus >= v2.43.0 or Alertmanager >= 0.25.0.
    #[serde(default)]
    pub proxy_from_environment: Option<bool>,
    /// `proxyURL` defines the HTTP proxy server to use.
    #[serde(default)]
    pub proxy_url: Option<String>,
    /// `scopes` defines the OAuth2 scopes used for the token request.
    #[serde(default)]
    pub scopes: Option<Vec<String>>,
    /// TLS configuration to use when connecting to the OAuth2 server.
    /// It requires Prometheus >= v2.43.0.
    #[serde(default)]
    pub tls_config: Option<PodMonitorPodMetricsEndpointsItemOauth2TlsConfig>,
    /// `tokenURL` configures the URL to fetch the token from.
    pub token_url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorPodMetricsEndpointsItemRelabelingsItemActionKind {
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "Replace")]
    ReplaceV1,
    #[serde(rename = "keep")]
    Keep,
    #[serde(rename = "Keep")]
    KeepV1,
    #[serde(rename = "drop")]
    Drop,
    #[serde(rename = "Drop")]
    DropV1,
    #[serde(rename = "hashmod")]
    Hashmod,
    #[serde(rename = "HashMod")]
    HashMod,
    #[serde(rename = "labelmap")]
    Labelmap,
    #[serde(rename = "LabelMap")]
    LabelMap,
    #[serde(rename = "labeldrop")]
    Labeldrop,
    #[serde(rename = "LabelDrop")]
    LabelDrop,
    #[serde(rename = "labelkeep")]
    Labelkeep,
    #[serde(rename = "LabelKeep")]
    LabelKeep,
    #[serde(rename = "lowercase")]
    Lowercase,
    #[serde(rename = "Lowercase")]
    LowercaseV1,
    #[serde(rename = "uppercase")]
    Uppercase,
    #[serde(rename = "Uppercase")]
    UppercaseV1,
    #[serde(rename = "keepequal")]
    Keepequal,
    #[serde(rename = "KeepEqual")]
    KeepEqual,
    #[serde(rename = "dropequal")]
    Dropequal,
    #[serde(rename = "DropEqual")]
    DropEqual,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemRelabelingsItem {
    /// Action to perform based on the regex matching.
    /// 
    /// `Uppercase` and `Lowercase` actions require Prometheus >= v2.36.0.
    /// `DropEqual` and `KeepEqual` actions require Prometheus >= v2.41.0.
    /// 
    /// Default: "Replace"
    #[serde(default)]
    pub action: Option<PodMonitorPodMetricsEndpointsItemRelabelingsItemActionKind>,
    /// Modulus to take of the hash of the source label values.
    /// 
    /// Only applicable when the action is `HashMod`.
    #[serde(default)]
    pub modulus: Option<i64>,
    /// Regular expression against which the extracted value is matched.
    #[serde(default)]
    pub regex: Option<String>,
    /// Replacement value against which a Replace action is performed if the
    /// regular expression matches.
    /// 
    /// Regex capture groups are available.
    #[serde(default)]
    pub replacement: Option<String>,
    /// Separator is the string between concatenated SourceLabels.
    #[serde(default)]
    pub separator: Option<String>,
    /// The source labels select values from existing labels. Their content is
    /// concatenated using the configured Separator and matched against the
    /// configured regular expression.
    #[serde(default)]
    pub source_labels: Option<Vec<String>>,
    /// Label to which the resulting string is written in a replacement.
    /// 
    /// It is mandatory for `Replace`, `HashMod`, `Lowercase`, `Uppercase`,
    /// `KeepEqual` and `DropEqual` actions.
    /// 
    /// Regex capture groups are available.
    #[serde(default)]
    pub target_label: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorPodMetricsEndpointsItemSchemeKind {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "https")]
    Https,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfigCaConfigMap {
    /// The key to select.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the ConfigMap or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfigCaSecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfigCa {
    /// ConfigMap containing data to use for the targets.
    #[serde(default)]
    pub config_map: Option<PodMonitorPodMetricsEndpointsItemTlsConfigCaConfigMap>,
    /// Secret containing data to use for the targets.
    #[serde(default)]
    pub secret: Option<PodMonitorPodMetricsEndpointsItemTlsConfigCaSecret>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfigCertConfigMap {
    /// The key to select.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the ConfigMap or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfigCertSecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfigCert {
    /// ConfigMap containing data to use for the targets.
    #[serde(default)]
    pub config_map: Option<PodMonitorPodMetricsEndpointsItemTlsConfigCertConfigMap>,
    /// Secret containing data to use for the targets.
    #[serde(default)]
    pub secret: Option<PodMonitorPodMetricsEndpointsItemTlsConfigCertSecret>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfigKeySecret {
    /// The key of the secret to select from.  Must be a valid secret key.
    pub key: String,
    /// Name of the referent.
    /// This field is effectively required, but due to backwards compatibility is
    /// allowed to be empty. Instances of this type with an empty value here are
    /// almost certainly wrong.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(default)]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(default)]
    pub optional: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorPodMetricsEndpointsItemTlsConfigMaxVersionKind {
    #[serde(rename = "TLS10")]
    TLS10,
    #[serde(rename = "TLS11")]
    TLS11,
    #[serde(rename = "TLS12")]
    TLS12,
    #[serde(rename = "TLS13")]
    TLS13,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorPodMetricsEndpointsItemTlsConfigMinVersionKind {
    #[serde(rename = "TLS10")]
    TLS10,
    #[serde(rename = "TLS11")]
    TLS11,
    #[serde(rename = "TLS12")]
    TLS12,
    #[serde(rename = "TLS13")]
    TLS13,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItemTlsConfig {
    /// Certificate authority used when verifying server certificates.
    #[serde(default)]
    pub ca: Option<PodMonitorPodMetricsEndpointsItemTlsConfigCa>,
    /// Client certificate to present when doing client-authentication.
    #[serde(default)]
    pub cert: Option<PodMonitorPodMetricsEndpointsItemTlsConfigCert>,
    /// Disable target certificate validation.
    #[serde(default)]
    pub insecure_skip_verify: Option<bool>,
    /// Secret containing the client key file for the targets.
    #[serde(default)]
    pub key_secret: Option<PodMonitorPodMetricsEndpointsItemTlsConfigKeySecret>,
    /// Maximum acceptable TLS version.
    /// 
    /// It requires Prometheus >= v2.41.0.
    #[serde(default)]
    pub max_version: Option<PodMonitorPodMetricsEndpointsItemTlsConfigMaxVersionKind>,
    /// Minimum acceptable TLS version.
    /// 
    /// It requires Prometheus >= v2.35.0.
    #[serde(default)]
    pub min_version: Option<PodMonitorPodMetricsEndpointsItemTlsConfigMinVersionKind>,
    /// Used to verify the hostname for the targets.
    #[serde(default)]
    pub server_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorPodMetricsEndpointsItem {
    /// `authorization` configures the Authorization header credentials to use when
    /// scraping the target.
    /// 
    /// Cannot be set at the same time as `basicAuth`, or `oauth2`.
    #[serde(default)]
    pub authorization: Option<PodMonitorPodMetricsEndpointsItemAuthorization>,
    /// `basicAuth` configures the Basic Authentication credentials to use when
    /// scraping the target.
    /// 
    /// Cannot be set at the same time as `authorization`, or `oauth2`.
    #[serde(default)]
    pub basic_auth: Option<PodMonitorPodMetricsEndpointsItemBasicAuth>,
    /// `bearerTokenSecret` specifies a key of a Secret containing the bearer
    /// token for scraping targets. The secret needs to be in the same namespace
    /// as the PodMonitor object and readable by the Prometheus Operator.
    /// 
    /// Deprecated: use `authorization` instead.
    #[serde(default)]
    pub bearer_token_secret: Option<PodMonitorPodMetricsEndpointsItemBearerTokenSecret>,
    /// `enableHttp2` can be used to disable HTTP2 when scraping the target.
    #[serde(default)]
    pub enable_http2: Option<bool>,
    /// When true, the pods which are not running (e.g. either in Failed or
    /// Succeeded state) are dropped during the target discovery.
    /// 
    /// If unset, the filtering is enabled.
    /// 
    /// More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase
    #[serde(default)]
    pub filter_running: Option<bool>,
    /// `followRedirects` defines whether the scrape requests should follow HTTP
    /// 3xx redirects.
    #[serde(default)]
    pub follow_redirects: Option<bool>,
    /// When true, `honorLabels` preserves the metric's labels when they collide
    /// with the target's labels.
    #[serde(default)]
    pub honor_labels: Option<bool>,
    /// `honorTimestamps` controls whether Prometheus preserves the timestamps
    /// when exposed by the target.
    #[serde(default)]
    pub honor_timestamps: Option<bool>,
    /// Interval at which Prometheus scrapes the metrics from the target.
    /// 
    /// If empty, Prometheus uses the global scrape interval.
    #[serde(default)]
    pub interval: Option<String>,
    /// `metricRelabelings` configures the relabeling rules to apply to the
    /// samples before ingestion.
    #[serde(default)]
    pub metric_relabelings: Option<Vec<PodMonitorPodMetricsEndpointsItemMetricRelabelingsItem>>,
    /// `oauth2` configures the OAuth2 settings to use when scraping the target.
    /// 
    /// It requires Prometheus >= 2.27.0.
    /// 
    /// Cannot be set at the same time as `authorization`, or `basicAuth`.
    #[serde(default)]
    pub oauth2: Option<PodMonitorPodMetricsEndpointsItemOauth2>,
    /// `params` define optional HTTP URL parameters.
    #[serde(default)]
    pub params: Option<std::collections::HashMap<String, Vec<String>>>,
    /// HTTP path from which to scrape for metrics.
    /// 
    /// If empty, Prometheus uses the default value (e.g. `/metrics`).
    #[serde(default)]
    pub path: Option<String>,
    /// The `Pod` port name which exposes the endpoint.
    /// 
    /// It takes precedence over the `portNumber` and `targetPort` fields.
    #[serde(default)]
    pub port: Option<String>,
    /// The `Pod` port number which exposes the endpoint.
    #[serde(default)]
    pub port_number: Option<i64>,
    /// `proxyURL` configures the HTTP Proxy URL (e.g.
    /// "http://proxyserver:2195") to go through when scraping the target.
    #[serde(default)]
    pub proxy_url: Option<String>,
    /// `relabelings` configures the relabeling rules to apply the target's
    /// metadata labels.
    /// 
    /// The Operator automatically adds relabelings for a few standard Kubernetes fields.
    /// 
    /// The original scrape job's name is available via the `__tmp_prometheus_job_name` label.
    /// 
    /// More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
    #[serde(default)]
    pub relabelings: Option<Vec<PodMonitorPodMetricsEndpointsItemRelabelingsItem>>,
    /// HTTP scheme to use for scraping.
    /// 
    /// `http` and `https` are the expected values unless you rewrite the
    /// `__scheme__` label via relabeling.
    /// 
    /// If empty, Prometheus uses the default value `http`.
    #[serde(default)]
    pub scheme: Option<PodMonitorPodMetricsEndpointsItemSchemeKind>,
    /// Timeout after which Prometheus considers the scrape to be failed.
    /// 
    /// If empty, Prometheus uses the global scrape timeout unless it is less
    /// than the target's scrape interval value in which the latter is used.
    #[serde(default)]
    pub scrape_timeout: Option<String>,
    /// Name or number of the target port of the `Pod` object behind the Service, the
    /// port must be specified with container port property.
    /// 
    /// Deprecated: use 'port' or 'portNumber' instead.
    #[serde(default)]
    pub target_port: Option<serde_json::Value>,
    /// TLS configuration to use when scraping the target.
    #[serde(default)]
    pub tls_config: Option<PodMonitorPodMetricsEndpointsItemTlsConfig>,
    /// `trackTimestampsStaleness` defines whether Prometheus tracks staleness of
    /// the metrics that have an explicit timestamp present in scraped data.
    /// Has no effect if `honorTimestamps` is false.
    /// 
    /// It requires Prometheus >= v2.48.0.
    #[serde(default)]
    pub track_timestamps_staleness: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorScrapeProtocolsItemKind {
    #[serde(rename = "PrometheusProto")]
    PrometheusProto,
    #[serde(rename = "OpenMetricsText0.0.1")]
    OpenMetricsText001,
    #[serde(rename = "OpenMetricsText1.0.0")]
    OpenMetricsText100,
    #[serde(rename = "PrometheusText0.0.4")]
    PrometheusText004,
    #[serde(rename = "PrometheusText1.0.0")]
    PrometheusText100,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorSelectorMatchExpressionsItem {
    /// key is the label key that the selector applies to.
    pub key: String,
    /// operator represents a key's relationship to a set of values.
    /// Valid operators are In, NotIn, Exists and DoesNotExist.
    pub operator: String,
    /// values is an array of string values. If the operator is In or NotIn,
    /// the values array must be non-empty. If the operator is Exists or DoesNotExist,
    /// the values array must be empty. This array is replaced during a strategic
    /// merge patch.
    #[serde(default)]
    pub values: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodMonitorSelector {
    /// matchExpressions is a list of label selector requirements. The requirements are ANDed.
    #[serde(default)]
    pub match_expressions: Option<Vec<PodMonitorSelectorMatchExpressionsItem>>,
    /// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
    /// map is equivalent to an element of matchExpressions, whose key field is "key", the
    /// operator is "In", and the values array contains only "value". The requirements are ANDed.
    #[serde(default)]
    pub match_labels: Option<std::collections::HashMap<String, String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PodMonitorSelectorMechanismKind {
    #[serde(rename = "RelabelConfig")]
    RelabelConfig,
    #[serde(rename = "RoleSelector")]
    RoleSelector,
}


/// Register every keyword form this domain exposes onto the host
/// interpreter. Embedders call this once during boot.
pub fn register() {
    tatara_lisp::domain::register::<PodMonitorSpec>();
}
